"""add_push_targets_and_push_target_ids

Revision ID: 798e23122f23
Revises: b2c3d4e5f6a7
Create Date: 2026-07-20 16:33:05.006191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '798e23122f23'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_jobs', sa.Column('push_target_ids', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_jobs', 'push_target_ids')
    # ### end Alembic commands ###
